name: Coana Vulnerability Analysis

on:
  schedule:
    - cron: '0 3 * * *' # every day at 3 AM
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manually run vulnerability analysis'
      # Required by the return-dispatch action
      distinct_id:

jobs:
  coana-vulnerability-analysis:
    runs-on: ubicloud-standard-8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup
        with:
          with-yarn: false
          install: true

      - name: Run Coana CLI
        id: coana-cli
        with:
          args: |
            npx @coana-tech/cli@latest run . \
              --api-key ${{ secrets.COANA_API_KEY }} \
              --repo-url https://github.com/${{github.repository}} \
              --memory-limit 8192
